DROP TABLE IF EXISTS USER;
CREATE TABLE USER
(
Id int NOT NULL,
Username varchar(255) NOT NULL,
Name varchar(255),
Password varchar(255),
Email varchar(255),
CONSTRAINT USERPK PRIMARY KEY (Id, Username)
);

DROP TABLE IF EXISTS ADMINISTRATOR;
CREATE TABLE ADMINISTRATOR
(
Id int NOT NULL,
Username varchar(255) NOT NULL,
CONSTRAINT ADMINPK PRIMARY KEY (Id, Username),
CONSTRAINT ADMINFK FOREIGN KEY (Id, Username)
	REFERENCES USER(Id, Username)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER
(
Id int NOT NULL,
Username varchar(255) NOT NULL,
CONSTRAINT CUSTOMERPK PRIMARY KEY (Id, Username),
CONSTRAINT CUSTOMERFK FOREIGN KEY (Id, Username)
	REFERENCES USER(Id, Username)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

DROP TABLE IF EXISTS SHIPPING_RECIPIENT;
CREATE TABLE SHIPPING_RECIPIENT
(
Name varchar(255) NOT NULL,
CustomerId int NOT NULL,
CustomerUsername varchar(255) NOT NULL,
City varchar(255),
Province varchar(255),
PostalCode varchar(255),
Street varchar(255),
StreetNumber int,
ApartmentNumber int,
CONSTRAINT SHIPPINGRECPK PRIMARY KEY (Name, CustomerId, CustomerUsername),
CONSTRAINT SHIPPINGRECFK FOREIGN KEY (CustomerId, CustomerUsername)
	REFERENCES CUSTOMER(Id, Username)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

DROP TABLE IF EXISTS ITEM;
CREATE TABLE ITEM
(
Id int NOT NULL,
Name varchar(255),
Price float,
ProductCategory varchar(255),
CONSTRAINT ITEMPK PRIMARY KEY (Id) 
);

DROP TABLE IF EXISTS BROWSES;
CREATE TABLE BROWSES
(
ItemId int NOT NULL,
CustomerId int NOT NULL,
CustomerUsername varchar(255) NOT NULL,
CONSTRAINT SHIPPINGRECPK PRIMARY KEY (ItemId, CustomerId, CustomerUsername),
CONSTRAINT SHIPPINGREC_ITEMFK FOREIGN KEY (ItemId)
	REFERENCES ITEM(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
CONSTRAINT SHIPPINGREC_CUSTOMERFK FOREIGN KEY (CustomerId, CustomerUsername)
	REFERENCES CUSTOMER(Id, Username)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

DROP TABLE IF EXISTS SHOPPING_CART;
CREATE TABLE SHOPPING_CART
(
CartId int NOT NULL,
ItemTotal int,
CustomerId int,
CustomerUsername varchar(255),
CONSTRAINT SHOPPING_CARTPK PRIMARY KEY (CartId),
CONSTRAINT SHOPPING_CARTFK FOREIGN KEY (CustomerId, CustomerUsername)
	REFERENCES CUSTOMER(Id, Username)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

DROP TABLE IF EXISTS ITEMS_IN_SHOPPING_CART;
CREATE TABLE ITEMS_IN_SHOPPING_CART
(
CartId int NOT NULL,
ItemId int NOT NULL,
CONSTRAINT ITEMS_IN_SHOPPING_CARTPK PRIMARY KEY (CartId, ItemId),
CONSTRAINT CARTIDFK FOREIGN KEY (CartId)
	REFERENCES SHOPPING_CART(CartId)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
CONSTRAINT ITEMIDFK FOREIGN KEY (ItemId)
	REFERENCES ITEM(Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

DROP TABLE IF EXISTS CREDIT_CARD_COMPANY;
CREATE TABLE CREDIT_CARD_COMPANY
(
Name varchar(255) NOT NULL,
City varchar(255),
Province varchar(255),
PostalCode varchar(255),
Street varchar(255),
StreetNumber int,
CONSTRAINT CREDIT_CARD_COMPANYPK PRIMARY KEY (Name)
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS
(
OrderId int NOT NULL,
TotalCost float,
CartId int,
CustomerId int,
CustomerUsername varchar(255),
CreditCardCompanyName varchar(255),
CONSTRAINT ORDERPK PRIMARY KEY (OrderId),
CONSTRAINT ORDER_SHOPPINGCARTFK FOREIGN KEY (CartId)
	REFERENCES SHOPPING_CART(CartId)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
CONSTRAINT ORDER_CUSTOMERFK FOREIGN KEY (CustomerId, CustomerUsername)
	REFERENCES CUSTOMER(Id, Username)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
CONSTRAINT ORDER_CREDITCARDCOMPFK FOREIGN KEY (CreditCardCompanyName)
	REFERENCES CREDIT_CARD_COMPANY(Name)
	ON DELETE SET NULL
	ON UPDATE CASCADE
);

DROP TABLE IF EXISTS SHIPMENT_COMPANY;
CREATE TABLE SHIPMENT_COMPANY
(
Name varchar(255) NOT NULL,
City varchar(255),
Province varchar(255),
PostalCode varchar(255),
Street varchar(255),
StreetNumber int,
CONSTRAINT SHIPMENT_COMPANYPK PRIMARY KEY (Name)
);

DROP TABLE IF EXISTS SHIPS;
CREATE TABLE SHIPS
(
ShipmentCompanyName varchar(255) NOT NULL,
OrderId int NOT NULL,
RecipientName varchar(255) NOT NULL,
CustomerId int NOT NULL,
CustomerUsername varchar(255) NOT NULL,
CONSTRAINT SHIPS_ORDERPK PRIMARY KEY (ShipmentCompanyName, OrderId, RecipientName, CustomerId, CustomerUsername),
CONSTRAINT SHIPS_SHIPCOMPFK FOREIGN KEY (ShipmentCompanyName)
	REFERENCES SHIPMENT_COMPANY(Name)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
CONSTRAINT SHIPS_SHIPRECFK FOREIGN KEY (RecipientName)
	REFERENCES SHIPPING_RECIPIENT(Name)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
CONSTRAINT SHIPS_CUSTOMERFK FOREIGN KEY (CustomerId, CustomerUsername)
	REFERENCES Customer(Id, Username)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
